defaults:
  - learningrate_monitor.yaml
  - model_checkpoint.yaml
  - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - write_h5_callback.yaml
  - _self_

learningrate_monitor:
  logging_interval: null
  log_momentum: false

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/loss"
  patience: 1000
  mode: "min"

model_summary:
  max_depth: -1

write_h5_callback:
  max_queue_size: 100
  max_concurrent_writers: 4
