name: mypy

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'No specific reason provided'

jobs:
  build:
    runs-on: ubuntu-latest
    name: mypy
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy
        python -m pip install -e ".[dev]"
    - name: mypy
      run: |
        mypy ahcore
